#!/usr/bin/env bash
# Install nginx and start it
sudo apt-get -y install nginx
service nginx start
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html
service nginx restart
